config/routes.rb
Rails.application.routes.draw do

  # customer側ルーティング
    devise_for :users, controllers: {
     sessions:      'users/sessions',
     passwords:     'users/passwords',
     registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end



  root 'top#about'
  get 'inquiry' => 'inquirys#index'
  post 'inquiry' => 'inquirys#create'
  get 'inquiry/thanks' => 'inquirys#thanks'
  get 'about' => 'top#about'
  post 'login' => 'joke_tmps#login'
  post 'joke_tmps/script' => 'joke_tmps#script'

  post 'joke_tmps/create' => 'joke_tmps#create'
  get 'joke_tmps/joke_first' => 'joke_tmps#joke_first'
  post 'joke_tmps/joke_middle' => 'joke_tmps#joke_middle'
  get 'joke_tmps/joke_last' => 'joke_tmps#joke_last'
  post 'joke_tmps/joke_last' => 'joke_tmps#create'

  resources :users, only: [:index, :edit, :update]
  get 'quit' => 'users#quit'
  patch 'users/withdraw' => 'users#withdraw'
  get 'users/joke_books/:id/:id' => 'joke_books#edit1'
  resources :joke_books, only: [:show, :index, :edit, :update, :destroy]
  resources :joke_tmps, only: [:index,  :new, :show, :edit, :update]



     # admin側ルーティング
     devise_for :admins, controllers: {
      sessions:      'admins/sessions',
      passwords:     'admins/passwords',
      registrations: 'admins/registrations'
   }

    namespace :admins do
     root :to => 'top#top'
     resources :users, only: [:index, :show, :edit, :update]
     resources :genres, only: [:index, :create, :edit, :update, :destroy]
     resources :joke_templetes, only: [:show, :new, :create, :edit, :update]
     get 'plan' => 'joke_templetes#plan'
     get 'show1/:id' => 'joke_templetes#show1'
     get 'inquiry/receive' => 'inquiry#receive'# 入力画面
    end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :joke_books
  has_many :joke_tmps
  has_many :inquiry

  def active_for_authentication?
    super && (self.is_users_status == true)
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
   @search = User.ransack(params[:q])
   @users = @search.result.page(params[:page]).per(10)
  end

  def show
   @user = User.find(params[:id])
  end

  def edit
   @user = User.find(params[:id])
  end

  def update
   @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admins_user_path(@user),
      notice: "ジャンル情報を更新しました！"
    else
      edit_admins_user_path(@user)
    end
  end

  private
  def user_params
    params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :is_users_status)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def new_guest
  user = User.find_or_create_by!(email: 'guest@changeguest.com', name: 'ゲスト') do |user|
    user.password = SecureRandom.urlsafe_base64
    # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
  end
  sign_in user
  redirect_to joke_tmps_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  # マイページへのアクション
  def index
    @user = current_user
    user = current_user
    @joke_books = user.joke_books
  end

  # 登録情報編集へのアクション
  def edit
    @user = current_user
  end

  # 登録情報の編集を保存するアクション
  def update
    @user = current_user
    if @user.update(user_params)
       flash[:success] = "登録情報を変更しました。"
       redirect_to users_path
    else
        render 'edit'
    end
  end

  # 登録情報編集画面から退会ページを表示するアクション
  def quit

  end

  # 退会アクション
  def withdraw
      @user = current_user

      # is_customer_statusカラムにフラグを立てる(default→false(有効状態)をtrue(無効状態)にする）
      @user.update(is_users_status: false)
      # ログアウトさせる
      reset_session

      flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
      redirect_to about_path
  end

  private
      def user_params
        params.permit(:name, :email, :is_users_status)
      end
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users/inquirys_helper.rb
module Users::InquirysHelper
end

app/helpers/users/scripts_helper.rb
module Users::ScriptsHelper
end

app/helpers/users/top_helper.rb
module Users::TopHelper
end

app/helpers/users/user_boke_tukkomis_helper.rb
module Users::UserBokeTukkomisHelper
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
end

app/views/users/edit.html.erb
<div class="row">
    <div class="col-xs-12">
      <h3 style="margin-left:0px;"><strong>登録情報編集</strong></h3>
      <%= form_with(model:@user, url:user_path ,method: :PATCH) do |f| %>
      <!-- local: trueがない場合、Rails5ではAjaxによる送信という意味になる。普通にHTMLとしてフォームを送信する場合にlocal: trueが必要になる-->
        <div>
            <div class="col-xs-12">
              <%= f.label :"氏名", class: "col-sm-3 control-label", style: "margin: 10px;" %>
              <%= f.text_field :name, class: "name col-sm-3 form-control-static name", style: "margin: 10px;" %>
            </div>
            <div class="col-xs-12">
              <%= f.label :"メールアドレス", class: "col-sm-3 control-label", style: "margin: 10px;" %>
              <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "col-sm-6 form-control-static", style: "margin: 10px;" %>
            </div>
        </div>

        <div class="actions col-xs-10 col-xs-offset-2">
        <p>
          <%= link_to " 戻る", quit_path, class: "glyphicon glyphicon-tint btn btn-danger col-sm-3", style: "margin: 10px;" %>

          <%= f.submit "編集内容を保存する", class: "btn btn-primary col-sm-3", style: "margin: 10px;" %>
        </p>
        </div>
      <% end %>
    </div>
</div>

app/views/users/index.html.erb
<div class="row" style="margin-top: 20px;">
  <div class="col-xs-10 col-xs-offset-1 col-xl-10 col-xl-offset-1">
    <p class="mypage" style="font-size: 30px;">マイページ</p>
    <p class="mypage" style="padding-left: 260px;"><%= link_to " 編集する", edit_user_path(current_user), class: "glyphicon glyphicon-pencil btn btn-success" %></p>
  </div>

  <div class="col-xs-10 col-xs-offset-1 col-xl-10 col-xl-offset-1">
    <div style="padding-top:10px;">
      <table class="table table-bordered table-condensed">
        <tr>
          <td class="col-xs-2">氏名</td>
          <td><%= current_user.name %></td>
        </tr>
        <tr>
          <td class="col-xs-2">メールアドレス</td>
          <td><%= current_user.email %></td>
        </tr>
      </table>
        <br>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-10 col-xs-offset-1 col-xl-10 col-xl-offset-1">
    <h3>完成ネタ一覧</h3>
    <h4>ここはご自身が作ったネタのみ表示されます！</h4>
  </div>

  <div class="col-xs-10 col-xs-offset-1 col-xl-10 col-xl-offset-1">
    <!-- ofsetは左右の余白 -->
  <% @joke_books.each do |joke_book| %>
  <% if joke_book.joke != nil %>
    <table class="table genre-index">
      <thead>
        <tr>
          <th>ネタ</th>
        </tr>
      </thead>

      <tbody>
          <tr>
            <td><%= link_to joke_book.name, joke_book_path(joke_book) %></td>
          </tr>
      </tbody>
    </table>
      <% end %>
      <% end %>
  </div>
</div>

app/views/users/quit.html.erb
<div class="row">
  <div class="col-xs-12">
    <h2><strong>本当に退会しますか？</strong></h2>
    <div class="messages">
        <h3>退会すると、会員登録情報や<br>
        これまでの購入履歴が閲覧できなくなります。<br>
        退会する場合は、「退会する」をクリックしてください。
        </h3>
    </div>

    <%= link_to "　退会しない", users_path, class: "glyphicon glyphicon-home btn btn-primary" %>
    <%= link_to "　退会する　", users_withdraw_path, method: :PATCH, data: {confirm: "本当に退会してもよろしいですか？"}, class: "glyphicon glyphicon-tint btn btn-danger" %>
  </div>
</div>