config/routes.rb
Rails.application.routes.draw do

  # customer側ルーティング
    devise_for :users, controllers: {
     sessions:      'users/sessions',
     passwords:     'users/passwords',
     registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end



  root 'top#about'
  get 'inquiry' => 'inquirys#index'
  post 'inquiry' => 'inquirys#create'
  get 'inquiry/thanks' => 'inquirys#thanks'
  get 'about' => 'top#about'
  post 'login' => 'joke_tmps#login'
  post 'joke_tmps/script' => 'joke_tmps#script'

  post 'joke_tmps/create' => 'joke_tmps#create'
  get 'joke_tmps/joke_first' => 'joke_tmps#joke_first'
  post 'joke_tmps/joke_middle' => 'joke_tmps#joke_middle'
  get 'joke_tmps/joke_last' => 'joke_tmps#joke_last'
  post 'joke_tmps/joke_last' => 'joke_tmps#create'

  resources :users, only: [:index, :edit, :update]
  get 'quit' => 'users#quit'
  patch 'users/withdraw' => 'users#withdraw'
  get 'users/joke_books/:id/:id' => 'joke_books#edit1'
  resources :joke_books, only: [:show, :index, :edit, :update, :destroy]
  resources :joke_tmps, only: [:index,  :new, :show, :edit, :update]



     # admin側ルーティング
     devise_for :admins, controllers: {
      sessions:      'admins/sessions',
      passwords:     'admins/passwords',
      registrations: 'admins/registrations'
   }

    namespace :admins do
     root :to => 'top#top'
     resources :users, only: [:index, :show, :edit, :update]
     resources :genres, only: [:index, :create, :edit, :update, :destroy]
     resources :joke_templetes, only: [:show, :new, :create, :edit, :update]
     get 'plan' => 'joke_templetes#plan'
     get 'show1/:id' => 'joke_templetes#show1'
     get 'inquiry/receive' => 'inquiry#receive'# 入力画面
    end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admins_joke.rb
class AdminsJoke < ApplicationRecord
  belongs_to :genre

  validates :introduction, {presence: true}
  validates :funny_man, {presence: true}
  validates :straight_man, {presence: true}
  validates :page, {presence: true}
end

app/views/admins/admins_jokes/edit.html.erb
<div class="row">
  <div class="col-xs-12">
    <h2>ボケ・ツッコミ編集</h2><br>
  </div>
</div>

<div class="row">
  <div class="col-xs-4">
    <%= form_for(@admins_joke, url: admins_admins_joke_path) do |f| %>
    <div class="boke_tukkomi-new-form">
       <img src="/assets/DSC_1170-1.jpg" width="320" height="220">
    </div>
  </div>

  <div class="col-xs-8">
      <table class="new-form-table">
        <tbody>

          <tr>
            <th>フリ</th>
            <td><%= f.text_field :introduction, class: "form-control" %></td>
          </tr>

          <tr>
            <th>ボケ</th>
            <td><%= f.text_field :funny_man, class: "form-control" %></td>
          </tr>

          <tr>
            <th>ツッコミ</th>
            <td><%= f.text_field :straight_man, class: "form-control" %></td>
          </tr>

          <tr>
            <th>ページ</th>
            <td><%= f.text_field :page, class: "form-control" %></td>
          </tr>

        </tbody>
      </table>

      <div class="text-right">
      <%= f.submit "更新" ,class: "btn btn-primary text-right" %>
      </div>
      <% end %>

  </div>
</div>

app/views/admins/admins_jokes/new.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1">
     <h2>ボケ・ツッコミ新規登録</h2><br>
  </div>
</div>

  <div class="row">
    <div class="col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1">
  <%= form_for(@admins_jokes, url: admins_plan_path) do |f| %>

  <div class="col-md-5 col-xs-5">
    <div class="boke_tukkomi-new-form">
      <img src="/assets/560893.jpg" width="320" height="220">
    </div>
  </div>

    <div class="col-md-5 col-xs-5">
      <table class="new-form-table">
        <tbody>

          <tr>
            <th>ジャンル</th>
            <td><%= f.collection_select :genre_id, Genre.all ,:id, :name, include_blank: "--選択してください--", class: "form-control" %></td>
          </tr>

          <tr>
            <th>フリ</th>
            <td><%= f.text_field :introduction, class: "form-control" %></td>
          </tr>

          <tr>
            <th>ボケ</th>
            <td><%= f.text_field :funny_man, class: "form-control" %></td>
          </tr>

          <tr>
            <th>ツッコミ</th>
            <td><%= f.text_field :straight_man, class: "form-control" %></td>
          </tr>

          <tr>
            <th>ページ</th>
            <td><%= f.text_field :page, class: "form-control" %></td>
          </tr>

        </tbody>
      </table>

      <br>
      <div class="text-right">
      <%= f.submit "新規登録" ,class: "btn btn-primary text-right" %>
      </div>
      <% end %>
      </div>
</div>
</div>

app/views/admins/admins_jokes/plan.html.erb
<div class="pull-right" style="text-align: right;">
	<%= search_form_for(@search, url:admins_plan_path) do |f| %>
		<%= f.label :name, "キーワード" %>
		<%= f.search_field :name_cont %>
		<%= f.submit %>
	<% end %>
</div>

<div class="row">
  <div class="col-xs-10 col-xs-offset-1">

    <h2>シーン選択画面</h2><br>

  </div>
</div>

<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
    <!-- ofsetは左右の余白 -->
    <table class="table genre-index">
      <thead>
        <tr>
          <th>ジャンル</th>
          <th>設定</th>
        </tr>
      </thead>

      <tbody>

        <% @genres.each do |genre| %>
        <% if genre.status == true %>
          <tr>
            <td><%= genre.category %></td>

            <td><%= link_to genre.name,admins_admins_joke_path(genre) %></td>

          </tr>
          <% end %>
          <% end %>
          <%= paginate @genres %>
      </tbody>
    </table>
</div>
</div>

app/views/admins/admins_jokes/show.html.erb
<div class="pull-right" style="text-align: right;">
	<%= search_form_for(@search, url:admins_admins_joke_path) do |f| %>
		<%= f.label :funny_man, "キーワード" %>
		<%= f.search_field :funny_man_cont %>
		<%= f.submit %>
	<% end %>
</div>

<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
      <h2>ボケ・ツッコミ一覧</h2>

  <div class="text-right">
      <%= link_to "新規登録" ,new_admins_admins_joke_path, class:"btn btn-lg btn-primary" %>
  </div>
	</div>
</div>

<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
      <!-- ofsetは左右の余白 -->
      <table class="table">
        <thead>
          <tr>
            <th>ストーリー名</th>
						<th>フリ</th>
            <th>ボケ</th>
            <th>ツッコミ</th>
          </tr>
        </thead>

        <tbody>
          <% @admins_jokes.each do |admins_joke| %>
					<% if @genre.id == admins_joke.genre.id %>
            <tr>
              <td><%= link_to admins_joke.id,admins_path(admins_joke)  %></td>
							<td><%= admins_joke.introduction %></td>
              <td><%= admins_joke.funny_man %></td>
              <td><%= admins_joke.straight_man %></td>
            </tr>
            <% end %>
						<% end %>
            <%= paginate @admins_jokes %>
        </tbody>
      </table>
    </div>
  </div>

app/views/admins/admins_jokes/show1.html.erb
<div class="row">
  <div class="col-xs-12">
      <h2>ボケ・ツッコミ詳細</h2><br>
  </div>
</div>

<div class="row">
    <div class="col-xs-4">
      <div class="boke_tukkomi-new-form">
        <img src="/assets/8cbafb69adb00b088d37d3a1f673deba.jpg" width="320" height="220">
      </div>
    </div>

      <div class="col-xs-8">
        <table class="table">
          <tbody>
            <tr>
              <td>題材名</td>
              <td><%= @admins_joke.genre.name %></td>
            </tr>

            <tr>
              <td>ジャンル</td>
              <td><%= @admins_joke.genre.category %></td>
            </tr>

            <tr>
              <td>フリ</td>
              <td><%= @admins_joke.introduction %></td>
            </tr>

            <tr>
              <td>ボケ</td>
              <td><%= @admins_joke.funny_man %></td>
            </tr>

            <tr>
              <td>ツッコミ</td>
              <td><%= @admins_joke.straight_man %></td>
            </tr>

            <tr>
              <td>ページ</td>
              <td><%= @admins_joke.page %></td>
            </tr>

          </tbody>
        </table>
        <div class="col-xs-offset-1 col-
          xs-2 text-right">
          <%= link_to "編集する", edit_admins_admins_joke_path(@admins_joke), class: "btn btn-primary" %>
        </div>
      </div>
</div>